### ISSUE TITLE
请问是否有相关论文能够读下该代码原理？

### ISSUE THREAD

**Issue by jimmy-walker** [pingbu/SimpleNLP#2]
您好，打搅了，请问是否有相关论文能够读下该代码原理？

**Comment by pingbu** [comment]
非常抱歉还没有撰写该代码相关文章，如有具体问题欢迎交流。（加微信pingbu）

**Comment by jimmy-walker** [comment]
不好意思。我微信加您了。但是发出去是红色感叹号。我能否留下自己的微信给您呢？（微信jomei7）
